// fichajes-bot Telegram Worker v3.1
// Cloudflare Workers + grammy + D1 native binding

import { Bot, webhookCallback, Context } from "grammy";

export interface Env {
  DB: D1Database;
  TELEGRAM_BOT_TOKEN: string;
  TELEGRAM_CHAT_ID_ALLOWED: string;
}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const bot = new Bot<Context>(env.TELEGRAM_BOT_TOKEN);

    // ── Security: solo Pejo ──────────────────────────────────────────
    bot.use(async (ctx, next) => {
      const allowedId = env.TELEGRAM_CHAT_ID_ALLOWED;
      if (String(ctx.chat?.id) !== allowedId) return;
      await next();
    });

    // ── /start ───────────────────────────────────────────────────────
    bot.command("start", async (ctx) => {
      await ctx.reply(
        "🏆 *Fichajes Bot v3.1 — Real Madrid Transfer Intelligence*\n\n" +
        "Comandos disponibles:\n" +
        "/top — Top 20 fichajes probables\n" +
        "/salidas — Top 10 salidas probables\n" +
        "/explain _nombre_ — Razonamiento completo\n" +
        "/detalle _nombre_ — Info completa\n" +
        "/historico _nombre_ — Score 30 días\n" +
        "/sources _nombre_ — Fuentes del jugador\n" +
        "/castilla — Castilla movimientos\n" +
        "/juvenil — Juvenil A movimientos\n" +
        "/cedidos — Canteranos cedidos\n" +
        "/debut\\_watch — Próximos debuts cantera\n" +
        "/economia — Estado modelo económico\n" +
        "/silencio — Pausar/reanudar alertas\n" +
        "/status — Estado del sistema\n" +
        "/feedback _texto_ — Enviar feedback",
        { parse_mode: "Markdown" }
      );
    });

    // ── /top ─────────────────────────────────────────────────────────
    bot.command("top", async (ctx) => {
      const rows = await env.DB.prepare(`
        SELECT nombre_canonico, score_smoothed, tipo_operacion_principal,
               club_actual, posicion, flags
        FROM jugadores
        WHERE tipo_operacion_principal = 'FICHAJE'
          AND entidad = 'primer_equipo'
          AND score_smoothed >= 0.10
          AND is_active = 1
        ORDER BY score_smoothed DESC LIMIT 20
      `).all();

      if (!rows.results.length) {
        await ctx.reply("No hay fichajes en el radar todavía. El sistema está calentando motores. 🔄");
        return;
      }

      const lines = rows.results.map((r: any, i: number) => {
        const pct = Math.round(r.score_smoothed * 100);
        const em = pct >= 70 ? "🟢" : pct >= 40 ? "🟡" : "🔴";
        const flags = JSON.parse(r.flags || "[]") as string[];
        const flagStr = flags.includes("POSIBLE_GLOBO_SONDA") ? " 🎭" : "";
        const posStr = r.posicion ? ` · ${r.posicion}` : "";
        return `${i + 1}. ${em} *${r.nombre_canonico}*${posStr} · ${pct}%${flagStr}`;
      });

      const now = new Date().toLocaleDateString("es-ES", {
        day: "2-digit", month: "2-digit", year: "numeric"
      });

      const msg = `🏆 *TOP 20 FICHAJES · ${now}*\n━━━━━━━━━━━━━━━━━\n\n${lines.join("\n")}\n\n_/explain <nombre> para análisis completo_`;
      await ctx.reply(msg, { parse_mode: "Markdown" });
    });

    // ── /salidas ──────────────────────────────────────────────────────
    bot.command("salidas", async (ctx) => {
      const rows = await env.DB.prepare(`
        SELECT nombre_canonico, score_smoothed, club_actual, posicion
        FROM jugadores
        WHERE tipo_operacion_principal = 'SALIDA'
          AND entidad = 'primer_equipo'
          AND score_smoothed >= 0.10
          AND is_active = 1
        ORDER BY score_smoothed DESC LIMIT 10
      `).all();

      if (!rows.results.length) {
        await ctx.reply("No hay salidas significativas en el radar.");
        return;
      }

      const lines = rows.results.map((r: any, i: number) => {
        const pct = Math.round(r.score_smoothed * 100);
        const em = pct >= 70 ? "🔴" : pct >= 40 ? "🟡" : "🟢";
        return `${i + 1}. ${em} *${r.nombre_canonico}* · ${pct}%`;
      });

      const msg = `📤 *TOP SALIDAS · Real Madrid*\n━━━━━━━━━━━━━━━━━\n\n${lines.join("\n")}`;
      await ctx.reply(msg, { parse_mode: "Markdown" });
    });

    // ── /explain ─────────────────────────────────────────────────────
    // Uses explanation_cache (pre-generated by precompute_explanations job, TTL 4h).
    // Cache hit → responds in <100ms. Cache miss → generates inline from D1.
    // Cache TTL for inline generation: 2h.
    bot.command("explain", async (ctx) => {
      const nombre = ctx.match?.trim();
      if (!nombre) {
        await ctx.reply("Uso: /explain <nombre_jugador>\nEjemplo: /explain Bellingham");
        return;
      }

      const jugador = await env.DB.prepare(`
        SELECT * FROM jugadores
        WHERE LOWER(nombre_canonico) LIKE LOWER(?) OR LOWER(slug) = LOWER(?)
        LIMIT 1
      `).bind(`%${nombre}%`, nombre).first<any>();

      if (!jugador) {
        await ctx.reply(`No encontrado: "${nombre}"\nUsa /top para ver los nombres exactos.`);
        return;
      }

      // Try cache first (TTL 2h for Worker responses; 4h for precomputed)
      const cached = await env.DB.prepare(`
        SELECT contenido, valido_hasta FROM explanation_cache
        WHERE jugador_id = ?
          AND valido_hasta > datetime('now')
        LIMIT 1
      `).bind(jugador.jugador_id).first<any>();

      if (cached?.contenido) {
        const chunks = splitMessage(cached.contenido);
        for (const chunk of chunks) {
          await ctx.reply(chunk, { parse_mode: "Markdown" });
        }
        return;
      }

      // Cache miss — generate inline
      const fullMsg = await generateExplainInline(jugador, env.DB);

      // Store in cache with 2h TTL
      const validoHasta = new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString();
      await env.DB.prepare(`
        INSERT INTO explanation_cache (jugador_id, contenido, generado_at, valido_hasta)
        VALUES (?, ?, datetime('now'), ?)
        ON CONFLICT(jugador_id) DO UPDATE SET
          contenido = excluded.contenido,
          generado_at = excluded.generado_at,
          valido_hasta = excluded.valido_hasta
      `).bind(jugador.jugador_id, fullMsg, validoHasta).run();

      const chunks = splitMessage(fullMsg);
      for (const chunk of chunks) {
        await ctx.reply(chunk, { parse_mode: "Markdown" });
      }
    });

    // ── /status ──────────────────────────────────────────────────────
    bot.command("status", async (ctx) => {
      const metrics = await env.DB.prepare(`
        SELECT metric_name, value, timestamp
        FROM metricas_sistema
        WHERE metric_name IN (
          'last_hot_loop_at', 'last_cold_loop_at',
          'rumores_procesados_hoy', 'gemini_calls_hoy',
          'sources_activas', 'sources_degradadas'
        )
        ORDER BY timestamp DESC
      `).all();

      const m: Record<string, any> = {};
      for (const row of metrics.results as any[]) {
        if (!m[row.metric_name]) m[row.metric_name] = row;
      }

      const jugadoresCount = await env.DB.prepare(
        "SELECT COUNT(*) as n FROM jugadores WHERE is_active=1"
      ).first<any>();

      // Última retractación detectada
      const lastRetraction = await env.DB.prepare(`
        SELECT j.nombre_canonico, r.retractado_at, p.nombre_completo as periodista
        FROM rumores r
        LEFT JOIN jugadores j ON r.jugador_id = j.jugador_id
        LEFT JOIN periodistas p ON r.periodista_id = p.periodista_id
        WHERE r.retractado = 1
        ORDER BY r.retractado_at DESC LIMIT 1
      `).first<any>();

      // Flags activos en el sistema
      const activeFlags = await env.DB.prepare(`
        SELECT flag_name, estado
        FROM flags_sistema
        WHERE estado != 'OFF'
        ORDER BY flag_name
      `).all();

      const retractionLine = lastRetraction
        ? `🚫 Última retractación: ${lastRetraction.nombre_canonico || "?"} (${lastRetraction.retractado_at?.split("T")[0] || "?"})`
        : `✅ Sin retractaciones recientes`;

      const flagLines = (activeFlags.results as any[]).length > 0
        ? `🚩 Flags activos: ${(activeFlags.results as any[]).map((f: any) => `${f.flag_name}=${f.estado}`).join(", ")}`
        : `✅ Sin flags activos`;

      const msg = [
        `⚙️ *Estado del sistema — Fichajes Bot v3.1*`,
        ``,
        `🔄 Último hot-loop: ${m.last_hot_loop_at?.value || "nunca"}`,
        `🌡️ Último cold-loop: ${m.last_cold_loop_at?.value || "nunca"}`,
        `📰 Rumores procesados hoy: ${m.rumores_procesados_hoy?.value || 0}`,
        `🤖 Calls Gemini hoy: ${m.gemini_calls_hoy?.value || 0}/1400`,
        `👥 Jugadores en radar: ${jugadoresCount?.n || 0}`,
        m.sources_degradadas?.value > 0
          ? `⚠️ Fuentes degradadas: ${m.sources_degradadas.value}`
          : `✅ Todas las fuentes operativas`,
        ``,
        retractionLine,
        flagLines,
      ].join("\n");

      await ctx.reply(msg, { parse_mode: "Markdown" });
    });

    // ── /castilla ────────────────────────────────────────────────────
    // Top 10 Castilla players with 3-way scores from factores_actuales
    bot.command("castilla", async (ctx) => {
      const rows = await env.DB.prepare(`
        SELECT nombre_canonico, posicion, edad, score_smoothed,
               factores_actuales, entidad_actual
        FROM jugadores
        WHERE (entidad = 'castilla' OR entidad_actual = 'castilla')
          AND is_active = 1
        ORDER BY score_smoothed DESC LIMIT 10
      `).all();

      if (!rows.results.length) {
        await ctx.reply("Sin datos de Castilla todavía.");
        return;
      }

      const now = new Date().toLocaleDateString("es-ES", { day: "2-digit", month: "2-digit" });
      const lines = (rows.results as any[]).map((r, i) => {
        const f = parseJSON(r.factores_actuales);
        const primer = Math.round((f.score_primer_equipo ?? 0) * 100);
        const stays  = Math.round((f.score_castilla_stays  ?? 0) * 100);
        const salida = Math.round((f.score_salida_o_cesion ?? 0) * 100);
        const emPrimer = primer >= 40 ? "🟢" : primer >= 20 ? "🟡" : "🔴";
        const emSalida = salida >= 50 ? "📤" : "🔄";
        const pos = r.posicion ? ` · ${r.posicion}` : "";
        const edad = r.edad ? ` (${r.edad}a)` : "";
        return (
          `${i + 1}. *${r.nombre_canonico}*${edad}${pos}\n` +
          `   ${emPrimer} 1er equipo: ${primer}% · 🏟️ Castilla: ${stays}% · ${emSalida} Salida: ${salida}%`
        );
      });

      const msg = `🏟️ *CASTILLA · ${now}*\n━━━━━━━━━━━━━━━━━\n\n${lines.join("\n\n")}\n\n_🟢/🟡/🔴 debut · 📤 salida/cesión_`;
      const chunks = splitMessage(msg);
      for (const chunk of chunks) await ctx.reply(chunk, { parse_mode: "Markdown" });
    });

    // ── /juvenil ────────────────────────────────────────────────────
    // Top 10 Juvenil A players with 3-way scores
    bot.command("juvenil", async (ctx) => {
      const rows = await env.DB.prepare(`
        SELECT nombre_canonico, posicion, edad, score_smoothed,
               factores_actuales, entidad_actual
        FROM jugadores
        WHERE (entidad = 'juvenil_a' OR entidad_actual = 'juvenil_a')
          AND is_active = 1
        ORDER BY score_smoothed DESC LIMIT 10
      `).all();

      if (!rows.results.length) {
        await ctx.reply("Sin datos de Juvenil A todavía.");
        return;
      }

      const now = new Date().toLocaleDateString("es-ES", { day: "2-digit", month: "2-digit" });
      const lines = (rows.results as any[]).map((r, i) => {
        const f = parseJSON(r.factores_actuales);
        const primer = Math.round((f.score_primer_equipo ?? 0) * 100);
        const stays  = Math.round((f.score_castilla_stays  ?? 0) * 100);
        const salida = Math.round((f.score_salida_o_cesion ?? 0) * 100);
        const emPrimer = primer >= 40 ? "🟢" : primer >= 20 ? "🟡" : "🔴";
        const emSalida = salida >= 50 ? "📤" : "🔄";
        const pos = r.posicion ? ` · ${r.posicion}` : "";
        const edad = r.edad ? ` (${r.edad}a)` : "";
        return (
          `${i + 1}. *${r.nombre_canonico}*${edad}${pos}\n` +
          `   ${emPrimer} Castilla/1er: ${primer}% · 🏅 Juvenil: ${stays}% · ${emSalida} Salida: ${salida}%`
        );
      });

      const msg = `⭐ *JUVENIL A · ${now}*\n━━━━━━━━━━━━━━━━━\n\n${lines.join("\n\n")}\n\n_🟢/🟡/🔴 ascenso · 📤 salida/cesión_`;
      const chunks = splitMessage(msg);
      for (const chunk of chunks) await ctx.reply(chunk, { parse_mode: "Markdown" });
    });

    // ── /debut_watch ─────────────────────────────────────────────────
    // Top 5 candidates for first-team debut sorted by score_primer_equipo
    bot.command("debut_watch", async (ctx) => {
      const rows = await env.DB.prepare(`
        SELECT nombre_canonico, posicion, edad, score_smoothed,
               factores_actuales, entidad, entidad_actual
        FROM jugadores
        WHERE (entidad IN ('castilla', 'juvenil_a')
               OR entidad_actual IN ('castilla', 'juvenil_a'))
          AND is_active = 1
        ORDER BY score_smoothed DESC LIMIT 30
      `).all();

      if (!rows.results.length) {
        await ctx.reply("Sin candidatos a debut identificados actualmente.");
        return;
      }

      // Sort by score_primer_equipo from factores_actuales, take top 5
      const sorted = (rows.results as any[])
        .map(r => ({ ...r, _f: parseJSON(r.factores_actuales) }))
        .sort((a, b) => (b._f.score_primer_equipo ?? 0) - (a._f.score_primer_equipo ?? 0))
        .slice(0, 5);

      const next = new Date();
      next.setDate(next.getDate() + (6 - next.getDay() + 6) % 7 + 1); // next weekend
      const nextStr = next.toLocaleDateString("es-ES", { weekday: "short", day: "2-digit", month: "2-digit" });

      const lines = sorted.map((r, i) => {
        const primer = Math.round((r._f.score_primer_equipo ?? 0) * 100);
        const em = primer >= 50 ? "🟢" : primer >= 30 ? "🟡" : "🔴";
        const nivel = (r.entidad_actual || r.entidad) === "castilla" ? "Castilla" : "Juvenil A";
        const pos = r.posicion ? ` · ${r.posicion}` : "";
        const edad = r.edad ? ` (${r.edad}a)` : "";
        return `${i + 1}. 🎯 *${r.nombre_canonico}*${edad}${pos} [${nivel}]\n   ${em} Debut 1er equipo: ${primer}%`;
      });

      const msg = [
        `🎯 *DEBUT WATCH — Top 5 candidatos*`,
        `━━━━━━━━━━━━━━━━━`,
        ``,
        lines.join("\n\n"),
        ``,
        `_Próximo partido relevante: ${nextStr}_`,
        `_/castilla o /juvenil para ver todos los 3 scores_`,
      ].join("\n");

      const chunks = splitMessage(msg);
      for (const chunk of chunks) await ctx.reply(chunk, { parse_mode: "Markdown" });
    });

    // ── /cedidos ────────────────────────────────────────────────────
    // Cedidos list with season metrics from rendimiento_cedidos
    bot.command("cedidos", async (ctx) => {
      const rows = await env.DB.prepare(`
        SELECT j.nombre_canonico, j.posicion, j.edad,
               rc.club_cesion, rc.temporada,
               rc.partidos, rc.minutos, rc.goles, rc.asistencias,
               rc.rating_medio, rc.lesion_larga, rc.actualizado_at
        FROM jugadores j
        LEFT JOIN rendimiento_cedidos rc ON j.jugador_id = rc.jugador_id
        WHERE j.entidad = 'cedido' AND j.is_active = 1
        ORDER BY rc.rating_medio DESC NULLS LAST LIMIT 15
      `).all();

      if (!rows.results.length) {
        await ctx.reply("Sin cedidos registrados actualmente.");
        return;
      }

      const lines = (rows.results as any[]).map((r, i) => {
        const club = r.club_cesion || "club desconocido";
        const partidos = r.partidos ?? "?";
        const minutos  = r.minutos  ?? "?";
        const goles    = r.goles    ?? "?";
        const asist    = r.asistencias ?? "?";
        const rating   = r.rating_medio != null ? r.rating_medio.toFixed(1) : "?";
        const lesion   = r.lesion_larga ? " ⚕️" : "";
        const emRating = r.rating_medio != null
          ? (r.rating_medio >= 7.5 ? "🟢" : r.rating_medio >= 6.5 ? "🟡" : "🔴")
          : "⚪";
        return (
          `${i + 1}. ${emRating} *${r.nombre_canonico}*${lesion} @ ${club}\n` +
          `   ${partidos}p · ${minutos}' · ⚽${goles} · 🅰️${asist} · ⭐${rating}`
        );
      });

      const msg = [
        `🔄 *CEDIDOS RM — Temporada actual*`,
        `━━━━━━━━━━━━━━━━━`,
        ``,
        lines.join("\n\n"),
        ``,
        `_🟢 rating ≥7.5 · 🟡 ≥6.5 · 🔴 <6.5 · ⚕️ lesionado_`,
      ].join("\n");

      const chunks = splitMessage(msg);
      for (const chunk of chunks) await ctx.reply(chunk, { parse_mode: "Markdown" });
    });

    // ── /economia ────────────────────────────────────────────────────
    bot.command("economia", async (ctx) => {
      const econ = await env.DB.prepare(
        "SELECT * FROM modelo_economico WHERE activo = 1 ORDER BY fecha_actualizacion DESC LIMIT 1"
      ).first<any>();

      if (!econ) {
        await ctx.reply("Modelo económico no disponible. El cold-loop lo cargará en el próximo ciclo.");
        return;
      }

      const msg = [
        `💰 *Modelo Económico RM · ${econ.temporada || "?"}*`,
        `_Actualizado: ${new Date(econ.fecha_actualizacion).toLocaleDateString("es-ES")}_`,
        `_Fuente: ${econ.fuente || "?"} (confianza ${Math.round((econ.confianza || 0) * 100)}%)_`,
        ``,
        `Tope salarial LaLiga: ${fmtM(econ.tope_laliga_rm)}`,
        `Masa salarial actual: ${fmtM(econ.masa_salarial_actual)}`,
        `Margen disponible: *${fmtM(econ.margen_salarial)}*`,
        `Presupuesto fichajes: *${fmtM(econ.presupuesto_fichajes_restante)}*`,
        ``,
        `Regla FFP: ${econ.regla_actual || "?"}`,
        `Política edad máx: ${econ.politica_edad_max || "?"}`,
      ].join("\n");

      await ctx.reply(msg, { parse_mode: "Markdown" });
    });

    // ── /silencio ────────────────────────────────────────────────────
    bot.command("silencio", async (ctx) => {
      const current = await env.DB.prepare(
        "SELECT estado FROM flags_sistema WHERE flag_name = 'alertas_realtime'"
      ).first<any>();

      const newState = current?.estado === "ENFORCE_HARD" ? "OFF" : "ENFORCE_HARD";
      await env.DB.prepare(
        "UPDATE flags_sistema SET estado = ?, actualizado_at = CURRENT_TIMESTAMP WHERE flag_name = 'alertas_realtime'"
      ).bind(newState).run();

      const msg = newState === "OFF"
        ? "🔕 Alertas pausadas. Usa /silencio para reactivar."
        : "🔔 Alertas reactivadas.";
      await ctx.reply(msg);
    });

    // ── /feedback ────────────────────────────────────────────────────
    bot.command("feedback", async (ctx) => {
      const text = ctx.match?.trim();
      if (!text) {
        await ctx.reply("Uso: /feedback <tu mensaje>\nEjemplo: /feedback El bot no registró el fichaje de X");
        return;
      }
      await env.DB.prepare(
        "INSERT INTO alertas_log (log_id, feedback_usuario, enviada_at) VALUES (?, ?, CURRENT_TIMESTAMP)"
      ).bind(crypto.randomUUID(), text).run();
      await ctx.reply("✅ Feedback registrado. Gracias Pejo 🏆");
    });

    // ── /detalle ─────────────────────────────────────────────────────
    bot.command("detalle", async (ctx) => {
      const nombre = ctx.match?.trim();
      if (!nombre) {
        await ctx.reply("Uso: /detalle <nombre_jugador>");
        return;
      }

      const jugador = await env.DB.prepare(`
        SELECT j.*, me.margen_salarial
        FROM jugadores j
        LEFT JOIN modelo_economico me ON me.activo=1
        WHERE LOWER(j.nombre_canonico) LIKE LOWER(?) OR LOWER(j.slug) = LOWER(?)
        LIMIT 1
      `).bind(`%${nombre}%`, nombre).first<any>();

      if (!jugador) {
        await ctx.reply(`No encontrado: "${nombre}"`);
        return;
      }

      const n_rumores = await env.DB.prepare(
        "SELECT COUNT(*) as n FROM rumores WHERE jugador_id=? AND retractado=0"
      ).bind(jugador.jugador_id).first<any>();

      const msg = [
        `📋 *Ficha: ${jugador.nombre_canonico}*`,
        `━━━━━━━━━━━━━━━━━━━━`,
        `Posición: ${jugador.posicion || "?"}`,
        `Club actual: ${jugador.club_actual || "?"}`,
        `Edad: ${jugador.edad || "?"}`,
        `Valor de mercado: ${fmtM(jugador.valor_mercado_m)}`,
        ``,
        `📊 Score: ${Math.round((jugador.score_smoothed || 0) * 100)}%`,
        `🎯 Tipo operación: ${jugador.tipo_operacion_principal}`,
        `📰 Rumores registrados: ${n_rumores?.n || 0}`,
        `🏷️ Primera mención: ${jugador.primera_mencion_at?.split("T")[0] || "?"}`,
        ``,
        `_/explain ${jugador.nombre_canonico} para análisis completo_`,
      ].join("\n");

      await ctx.reply(msg, { parse_mode: "Markdown" });
    });

    // ── /historico ───────────────────────────────────────────────────
    bot.command("historico", async (ctx) => {
      const nombre = ctx.match?.trim();
      if (!nombre) {
        await ctx.reply("Uso: /historico <nombre_jugador>");
        return;
      }

      const jugador = await env.DB.prepare(
        "SELECT jugador_id, nombre_canonico FROM jugadores WHERE LOWER(nombre_canonico) LIKE LOWER(?) LIMIT 1"
      ).bind(`%${nombre}%`).first<any>();

      if (!jugador) {
        await ctx.reply(`No encontrado: "${nombre}"`);
        return;
      }

      const hist = await env.DB.prepare(`
        SELECT score_nuevo, delta, razon_cambio, timestamp
        FROM score_history
        WHERE jugador_id = ?
        ORDER BY timestamp DESC LIMIT 30
      `).bind(jugador.jugador_id).all();

      if (!hist.results.length) {
        await ctx.reply("Sin historial disponible para este jugador.");
        return;
      }

      const scores = (hist.results as any[]).map(r => r.score_nuevo).reverse();
      const sparkline = buildSparkline(scores);

      const lines = (hist.results as any[]).slice(0, 10).map(r => {
        const pct = Math.round((r.score_nuevo || 0) * 100);
        const delta = r.delta ? (r.delta > 0 ? `+${Math.round(r.delta * 100)}` : `${Math.round(r.delta * 100)}`) : "0";
        const fecha = r.timestamp?.split("T")[0] || "?";
        return `${fecha}: ${pct}% (${delta}) — ${r.razon_cambio || "?"}`;
      });

      const msg = [
        `📈 *Histórico score: ${jugador.nombre_canonico}*`,
        `\`${sparkline}\``,
        ``,
        ...lines,
      ].join("\n");

      await ctx.reply(msg, { parse_mode: "Markdown" });
    });

    // ── /sources ─────────────────────────────────────────────────────
    bot.command("sources", async (ctx) => {
      const nombre = ctx.match?.trim();
      if (!nombre) {
        await ctx.reply("Uso: /sources <nombre_jugador>");
        return;
      }

      const jugador = await env.DB.prepare(
        "SELECT jugador_id, nombre_canonico FROM jugadores WHERE LOWER(nombre_canonico) LIKE LOWER(?) LIMIT 1"
      ).bind(`%${nombre}%`).first<any>();

      if (!jugador) {
        await ctx.reply(`No encontrado: "${nombre}"`);
        return;
      }

      const fuentes = await env.DB.prepare(`
        SELECT p.nombre_completo, p.tier, p.reliability_global,
               COUNT(r.rumor_id) as n_rumores,
               MAX(r.fecha_publicacion) as ultimo_rumor
        FROM rumores r
        JOIN periodistas p ON r.periodista_id = p.periodista_id
        WHERE r.jugador_id = ? AND r.retractado = 0
        GROUP BY r.periodista_id
        ORDER BY n_rumores DESC LIMIT 8
      `).bind(jugador.jugador_id).all();

      if (!fuentes.results.length) {
        await ctx.reply("Sin fuentes registradas para este jugador.");
        return;
      }

      const lines = (fuentes.results as any[]).map((f, i) => {
        const rel = Math.round((f.reliability_global || 0) * 100);
        const last = f.ultimo_rumor?.split("T")[0] || "?";
        return `${i + 1}. [${f.tier}] *${f.nombre_completo}* · ${rel}% fiabilidad · ${f.n_rumores} rumores · último: ${last}`;
      });

      await ctx.reply(
        `📡 *Fuentes: ${jugador.nombre_canonico}*\n━━━━━━━━━━━━━━━\n\n${lines.join("\n")}`,
        { parse_mode: "Markdown" }
      );
    });

    return webhookCallback(bot, "cloudflare-mod")(request);
  },
};

// ── Explain inline generation (cache miss path) ───────────────────────────

async function generateExplainInline(jugador: any, db: D1Database): Promise<string> {
  const pct = Math.round((jugador.score_smoothed || 0) * 100);
  const factores = parseJSON(jugador.factores_actuales);
  const flags = parseJSON(jugador.flags) as string[];

  // Score 7 days ago
  const hist7d = await db.prepare(`
    SELECT score_nuevo FROM score_history
    WHERE jugador_id = ? AND timestamp <= datetime('now', '-7 days')
    ORDER BY timestamp DESC LIMIT 1
  `).bind(jugador.jugador_id).first<any>();
  const score7d = hist7d?.score_nuevo;
  const deltaStr = score7d != null
    ? ` (${pct - Math.round(score7d * 100) >= 0 ? "▲" : "▼"}${Math.abs(pct - Math.round(score7d * 100))}% vs 7d)`
    : "";

  // Top 3 rumores
  const topRumores = await db.prepare(`
    SELECT r.lexico_detectado, r.peso_lexico, r.fecha_publicacion, r.tipo_senal,
           p.nombre_completo as periodista_nombre, p.reliability_global, p.tier
    FROM rumores r
    LEFT JOIN periodistas p ON r.periodista_id = p.periodista_id
    WHERE r.jugador_id = ? AND r.retractado = 0
    ORDER BY ABS(r.peso_lexico) DESC LIMIT 3
  `).bind(jugador.jugador_id).all();

  // Timeline last 10
  const timeline = await db.prepare(`
    SELECT r.fecha_publicacion, r.lexico_detectado, r.tipo_senal, r.retractado,
           p.nombre_completo as periodista_nombre, p.tier
    FROM rumores r
    LEFT JOIN periodistas p ON r.periodista_id = p.periodista_id
    WHERE r.jugador_id = ?
    ORDER BY r.fecha_publicacion DESC LIMIT 10
  `).bind(jugador.jugador_id).all();

  // Sparkline 30 days
  const sparkRows = await db.prepare(`
    SELECT score_nuevo FROM score_history
    WHERE jugador_id = ? AND timestamp >= datetime('now', '-30 days')
    ORDER BY timestamp ASC
  `).bind(jugador.jugador_id).all();
  const sparkScores = (sparkRows.results as any[]).map(r => r.score_nuevo);
  const sparkline = buildSparkline(sparkScores);

  const msg: string[] = [
    `🔬 *Análisis extendido: ${jugador.nombre_canonico}*`,
    `━━━━━━━━━━━━━━━━━━━━━━━━━━━━`,
    ``,
    `📊 *Score actual: ${pct}%*${deltaStr}`,
    `   raw: ${fmt(jugador.score_raw)} | smoothed: ${pct}%`,
    ``,
    `🧮 *Descomposición completa:*`,
    `├─ *Componentes:*`,
    `│  ├─ Consenso:        ${fmt(factores.consenso)}`,
    `│  ├─ Credibilidad:    ${fmt(factores.credibilidad)}`,
    `│  ├─ Fase rumor:      ${factores.fase_dominante ?? "?"}\/6`,
    `│  └─ Temporal:        ${fmt(factores.factor_temporal)}`,
    `├─ *Modificadores:*`,
    `│  ├─ Económico:       ${fmt(factores.factor_econ)}`,
    `│  ├─ Sustitución:     ${fmt(factores.factor_subst)}`,
    `│  ├─ Sesgo medio:     ${fmt(factores.bias_correction)}`,
    `│  ├─ Retractación:    ${fmt(factores.retraction_penalty)}`,
    `│  └─ Kalman P:        ${factores.kalman_P ?? "?"}`,
    ``,
  ];

  if (topRumores.results.length) {
    msg.push(`📰 *Top 3 rumores con más peso:*`);
    (topRumores.results as any[]).forEach((r, i) => {
      const fecha = (r.fecha_publicacion || "?").split("T")[0];
      const rel = fmt(r.reliability_global);
      msg.push(`${i + 1}. *${r.periodista_nombre || "?"}* (${r.tier || "?"}) · \`${r.lexico_detectado || "?"}\` · peso: ${fmt(r.peso_lexico)} · rel: ${rel} · ${fecha}`);
    });
    msg.push(``);
  }

  if ((timeline.results as any[]).length) {
    msg.push(`📅 *Timeline (últimos 10):*`);
    (timeline.results as any[]).forEach(r => {
      const fecha = (r.fecha_publicacion || "?").split("T")[0];
      const retracted = r.retractado ? " ~~retractado~~" : "";
      const tipo = r.tipo_senal || r.lexico_detectado || "?";
      msg.push(`• ${fecha} — *${r.periodista_nombre || "?"}* (${r.tier || "?"}) — \`${tipo}\`${retracted}`);
    });
    msg.push(``);
  }

  if (flags.length) {
    msg.push(`🚩 *Flags activos:*`);
    flags.forEach(f => msg.push(`• *${f}*`));
    msg.push(``);
  }

  if (sparkline) {
    msg.push(`📈 *Evolución 30d:* \`${sparkline}\``);
    msg.push(``);
  }

  return msg.join("\n");
}

// ── Utilities ──────────────────────────────────────────────────────────────

function fmt(v: number | null | undefined): string {
  if (v == null) return "?";
  return `${Math.round(v * 100)}%`;
}

function fmtM(v: number | null | undefined): string {
  if (v == null) return "?";
  return `${(v / 1_000_000).toFixed(0)}M€`;
}

function parseJSON(s: string | null | undefined): any {
  if (!s) return {};
  try { return JSON.parse(s); } catch { return {}; }
}

function buildSparkline(scores: number[]): string {
  if (!scores.length) return "";
  const chars = "▁▂▃▄▅▆▇█";
  const min = Math.min(...scores);
  const max = Math.max(...scores);
  const range = max - min || 0.01;
  return scores
    .map(s => chars[Math.min(7, Math.floor(((s - min) / range) * 8))])
    .join("");
}

function splitMessage(text: string, maxLen = 4000): string[] {
  if (text.length <= maxLen) return [text];
  const chunks: string[] = [];
  let current = "";
  for (const line of text.split("\n")) {
    if (current.length + line.length + 1 > maxLen) {
      chunks.push(current.trim());
      current = "";
    }
    current += line + "\n";
  }
  if (current.trim()) chunks.push(current.trim());
  return chunks;
}
